class muninclient::config {
    file { "$muninclient::params::configfile" :
        ensure => present,
    }
    file_line { "$muninclient::params::configfile" :
        path => "$muninclient::params::configfile",
        line => "# All thoses lines after this comment are auto-generated by puppet !",
        line => "# Please do not touch it !",
        line => "host_name $muninclient::params::muninclient_hostname",
        line => "allow $munninclient::params::muninclient_allowed_master",
}
